INSERT INTO delivery(products, owner_id) VALUES('fruit', 1);
INSERT INTO delivery(products, owner_id) VALUES('clothing', 1);
INSERT INTO delivery(products, owner_id) VALUES('tools', 2);
INSERT INTO delivery(products, owner_id) VALUES('electronics', 2);
INSERT INTO delivery(products, owner_id) VALUES('furniture', 3);
INSERT INTO delivery(products, owner_id) VALUES('vegetables', 4);
INSERT INTO delivery(products, owner_id) VALUES('toys', 5);
INSERT INTO delivery(products, owner_id) VALUES('cosmetics', 6);
INSERT INTO delivery(products, owner_id) VALUES('technique', 7);
INSERT INTO delivery(products, owner_id) VALUES('books', 7);
INSERT INTO delivery(products, owner_id) VALUES('stationery', 7);
INSERT INTO delivery(products, owner_id) VALUES('bags', 8);
INSERT INTO delivery(products, owner_id) VALUES('shoes', 8);
INSERT INTO delivery(products, owner_id) VALUES('watch', 9);
INSERT INTO delivery(products, owner_id) VALUES('mobile phone', 10);